### ISSUE TITLE
can not find esti_kernal.py under the kernelGan folder

### ISSUE THREAD

**Issue by ustcxiaofei** [geopi1/Improved_USRNet#1]

**Comment by geopi1** [comment]
Hi, 
this file does not exist in the original project either [https://github.com/sefibk/KernelGAN].
I can't see where this file is used or read.
Can you further elaborate on your problem?

George

**Comment by ustcxiaofei** [comment]
sorry for did not describe the problem clear.  in the main. py file,  line 3 'from kernelgan.est_kernel import estimate_kernel'.  but I do not find the definition of the function.  thanks a lot

**Comment by geopi1** [comment]
Thanks!
I added the file, indeed it was not pushed.
Tell if everything works I'll close the issue.

**Comment by ustcxiaofei** [comment]
now everything works well.  thanks a lot
